---
title: "House prices data explore"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(corrplot)
library(DT)
```

```{r}
# load data
df0 <- read_csv("../data/train.csv") %>%
  mutate(across(where(is.character), ~fct_infreq(.x)))
```

Feature explorer
=======================================================================

Input {.sidebar}
-----------------------------------------------------------------------

### Inputs

```{r}
selectInput(
  inputId = "feature",
  label = "Choose column",
  choices = names(df0) %>% sort()
)
```

```{r}
# filter data
feature_vals <- reactive({
  df0 %>% pull(input$feature)
})

# feature type
feature_type <- reactive({
  feature_vals() %>% class()
})

# number of distinct values
n_vals <- reactive({
  feature_plot_df() %>% pull(input$feature) %>% n_distinct()
})

# feature plot df
feature_plot_df <- reactive({
  df <- df0 %>%
    select(input$feature, SalePrice) %>%
    drop_na()
})
```

Row {data-height=125}
-----------------------------------------------------------------------

### Distinct values

```{r}
renderPrint({
  feature_vals() %>% n_distinct()
})
```

### Missing values

```{r}
renderPrint({
  sum(is.na(feature_vals()))
})
```

Row {data-height=600}
-----------------------------------------------------------------------

### Feature plot

```{r}
renderPlot({
  # create a plot based on the col type and number of distinct values
  if (feature_type() == "numeric" & n_vals() > 10) {
    g <- feature_plot_df() %>%
      ggplot(aes(x = !!sym(input$feature))) +
      geom_histogram(col = "black",
                     fill = "orange",
                     bins = 30)
  } else {
    g <- feature_plot_df() %>%
      ggplot(aes(y = !!sym(input$feature))) +
      geom_bar(col = "black", fill = "lightblue") +
      labs(y = input$feature)
  }
  # output the plot
  g
})
```

### Relationship with SalePrice

```{r}
renderPlot({
  plot_df <- df0 %>%
    filter(!is.na(input$feature))
  
  feature_type <- plot_df %>% pull(input$feature) %>% class()
  
  if(feature_type() == "numeric" & n_vals() > 10) {
    g <- feature_plot_df() %>%
      ggplot(
        aes(
          x = !!sym(input$feature),
          y = SalePrice
        )
      ) +
      geom_point() +
      geom_smooth(se = FALSE)
  } else {
    g <- feature_plot_df() %>%
      ggplot(
        aes(
          x = SalePrice,
          y = reorder(!!sym(input$feature), SalePrice)
        )
      ) +
      geom_boxplot() +
      labs(y = input$feature)
  }
  
  g
})
```

Row
-----------------------------------------------------------------------

### Data summary

```{r}
renderTable({
  # store the column values
  x <- feature_vals() %>% na.omit()
  
  if (feature_type() == "numeric") {
    feature_tbl <- tibble(
      stat = c("# vals", "mean", "sd", "min", "25%", "median", "75%", "max"),
      value = c(round(length(x)), mean(x), sd(x), min(x), quantile(x, probs = 0.25),
                median(x), quantile(x, probs = 0.75), max(x))
    )
  } else {
    feature_tbl <- df0 %>%
      count(!!sym(input$feature))
  }
  feature_tbl
})
```

### Correlation with SalePrice

```{r}
renderPrint({
  if(feature_type() == "numeric"){
    cor(feature_plot_df()[1], feature_plot_df()[2])
  } else {
    print("Selected input column is not numeric")
  }
})
```

Correlation between numeric variables
=======================================================================

Row
-----------------------------------------------------------------------

### Correlation plot (sorted by correlation with SalePrice)

```{r}
renderPlot({
  # sort by correlation with SalePrice
  cor_names <- map_dbl(df0 %>%
                         select(where(is.numeric), -Id),
                       ~cor(df0$SalePrice, .x, use = "pairwise.complete.obs")) %>%
    abs() %>%
    sort(decreasing = TRUE) %>% names()
  
  # compute pairwise correlations and cplot
  df0 %>%
    select(where(is.numeric), -Id) %>%
    select(all_of(cor_names)) %>%
    cor(use = "pairwise.complete.obs") %>%
    corrplot(tl.col = 'black',
             method = "pie",
             order = "original",
             type = "upper")
})
```

Missing and unique values
=======================================================================

Row
-----------------------------------------------------------------------

### Missing values

```{r}
renderPlot({
  tibble(
  x = rep(1:9, times = 9),
  y = rep(9:1, each = 9),
  name = sort(names(df0))
) %>%
  left_join(
    map_df(df0, ~ sum(is.na(.x))) %>%
      pivot_longer(
        cols = everything(),
        names_to = "name",
        values_to = "n_missing"
      ),
    by = "name"
  ) %>%
  mutate(prop_na = 100* round(n_missing / nrow(df0), 3)) %>%
  ggplot(
    aes(
      x = x,
      y = y,
      label = paste0(name, "\n", n_missing, " (", prop_na, "%)")
    )
  ) +
  geom_tile(aes(fill = prop_na, alpha = prop_na)) +
  geom_text(aes(col = prop_na > 0), size = 3) +
  scale_fill_gradient(low = "green", high = "red") +
  scale_color_manual(values = c("TRUE" = "blue", "FALSE" = "black")) +
  labs(fill = "Percent missing") +
  guides(alpha = "none", color = "none") +
  theme_void() +
  theme(legend.position = "top")
})
```

### Unique values

```{r}
renderPlot({
  tibble(
    x = rep(1:9, times = 9),
    y = rep(9:1, each = 9),
    name = sort(names(df0))
  ) %>%
    left_join(
      map_df(df0, ~ n_distinct(.x)) %>%
        pivot_longer(
          cols = everything(),
          names_to = "name",
          values_to = "n_unique"
        ),
      by = "name"
    ) %>%
    rowwise() %>%
    mutate(
      prop_unique = 100 * round(n_unique / nrow(df0), 3),
      class_type = class(df0 %>% pull(name))
    ) %>%
    ggplot(aes(
      x = x,
      y = y,
      label = paste0(name, "\n", n_unique, " (", prop_unique, "%)")
    )) +
    geom_tile(aes(fill = class_type), alpha = 0.5) +
    geom_text(aes(col = n_unique > 10), size = 3) +
    scale_fill_manual(values = c(factor = "lightblue", numeric = "orange")) +
    scale_color_manual(values = c("TRUE" = "blue", "FALSE" = "black")) +
    labs(fill = "Variable type") +
    guides(alpha = "none", col = "none") +
    theme_void() +
    theme(legend.position = "top")
})
```

Dataset
=======================================================================

Row
-----------------------------------------------------------------------

### Dataset

```{r}
renderDataTable({
  df0 %>%
    datatable(filter = 'top',
              options = list(pageLength = 12,
                             scrollY = '500px',
                             scrollX = TRUE))
})
```
